Add database
alanpodolsk/java-filmorate pull request #5
Opened 2023-07-07 22:37 UTC by alanpodolsk

2023-07-08 12:04 UTC, ohelly requested changes
Привет! Видно, что проделана большая работа. Есть несколько замечаний, которые необходимо исправить. Также я оставил ряд рекмомендаций, на которые стоит обратить внимание.
Основные проблемы в том, что выполняется много лишних запросов, а также не совсем корректное использование jdbcTemplate. JdbcTemplate уже предоставляет очень много функционала и поэтому не стоит использовать всегда один метод.

2023-07-08 12:04 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDaoImpl.java
> +    private RowMapper<List<Film>> filmRowMapper() {
Необходимо исправить: Предлагаю следующие доработки по методу filmRowMapper:
![image](https://github.com/alanpodolsk/java-filmorate/assets/51891976/9c3f77d8-79ef-4d0b-9e2e-29310206ae3b)
В твоем маппере очень много логики и очень много дополнительных запросов, что очень плохо сказаывается на производительности. 
Также нельзя доставать жанры внутри маппера, так как из за этого получается очень много запросов - на N фильмов выполнится N запросов для получения жанров. Необходимо всегда получать все жанры одним запросом независимо от количества фильмов. Как этого добиться:
В данном классемы делаем дополнительный метод:
![image](https://github.com/alanpodolsk/java-filmorate/assets/51891976/fc290489-365f-45d8-a4b6-d038244de48e)

Который затем можно использовать:

Тем самым мы достаем все жанры для всех фильмов одним запросом. Примеры использования:
![image](https://github.com/alanpodolsk/java-filmorate/assets/51891976/066df802-529d-4cdb-9d20-29047a6ec4ef)

2023-07-08 23:01 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDaoImpl.java
> +        String sqlQuery = "INSERT INTO users (name, email, login, birthday) " +
Исправлено

2023-07-08 23:02 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDaoImpl.java
> +    public List<User> getFriendsById(Integer id) {
Исправлено - Добавлена проверка на уровне сервиса DbUserService

2023-07-08 23:03 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDaoImpl.java
> +        } catch (RuntimeException e) {
Исправлено. Добавлен приватный метод, который возвращает именно id друзей, т.к. в User именно Set<Integer> friends, и на такое хранение заточены тесты Postman

2023-07-08 23:05 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDaoImpl.java
> +    public List<User> getMutualFriends(Integer userId, Integer otherUserId) {
Исправлено. Проверка добавлена на уровне сервиса. Маппер переписан под User вместо List

2023-07-08 23:08 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDaoImpl.java
> +        return user.getId();
Исправлено

2023-07-08 23:08 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDaoImpl.java
> +    public List<User> getAllUsers() {
Исправлено

2023-07-08 23:09 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/UserDaoImpl.java
> +            users = jdbcTemplate.queryForObject("SELECT u.id, u.name, u.email, u.login, u.birthday, f.friend_id " +
Исправлено

2023-07-08 23:09 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/service/DbUserService.java
> +        return userDao.getUserById(user.getId());
Исправлено

2023-07-08 23:09 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/MPADaoImpl.java
> +        } catch (RuntimeException e) {
Исправлено

2023-07-08 23:09 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/GenreDaoImpl.java
> +        } catch (RuntimeException e) {
Исправлено

2023-07-08 23:10 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +        Integer id = filmDao.addFilm(film);
Исправлено, однако в сервисе остался вызов getFilmById, т.к. это необходимо для прохождения тестов Postman

2023-07-08 23:29 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +        List<Film> films = filmDao.getAllFilms();
Исправлено. Добавлен метод в FilmDao

2023-07-08 23:30 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDaoImpl.java
> +        return (Integer) id;
Изменено, сделано по аналогии с addFilm

2023-07-08 23:31 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDaoImpl.java
> +        return film.getId();
Исправлено

2023-07-08 23:32 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDaoImpl.java
> +            List<Film> films = jdbcTemplate.queryForObject("SELECT f.id, f.name, f.description, f.releaseDate, f.duration, f.mpa_id, l.user_id, g.genre_id from films f left join likes l on f.id = l.f
Исправлено

2023-07-08 23:32 UTC, alanpodolsk commented on src/main/java/ru/yandex/practicum/filmorate/repository/FilmDaoImpl.java
> +    private RowMapper<List<Film>> filmRowMapper() {
Исправлено

2023-07-09 11:57 UTC, ohelly approved these changes
Привет! Все супер, работу принимаю. Можно двигаться дальше!

2023-07-10 06:36 UTC, merged